# postal-api-config.yaml
enabled: true
endpoint: "https://monocloud.email/api/v1/send/message"
auth-type: "api-key"
auth-token: "6ZosdBoQdzng6WqNUmFGvQNi"
api-key-header: "X-Server-API-Key"
timeout: 60
insecure-skip-verify: false

# Simple template for testing
request-template:
  template: |
    {
      "to": ["ahmet.soguksu@mono.tr"],
      "from": "test@otoanaliz.net.tr",
      "subject": "Test Email from Mailpit",
      "plain_body": "This is a test email sent via Mailpit API relay"
    }
  content-type: "application/json"
